example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user, add_task, change_status, delete_task, show_json, show_todolist_ajax, add_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('create-task/', add_task, name='add_task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('change-status/', change_status, name='change_status'),
    path('delete-task/', delete_task, name='delete_task'),
    path('json/', show_json, name='show_json'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path('add/', add_task_ajax, name='add_task_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.

class MyWatchList(models.Model):
    watched = models.TextField()
    title = models.TextField()
    rating = models.FloatField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    status = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Riona Adani Ghaisani',
        'npm' : '2106750995'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    data_watchlist = MyWatchList.objects.all()
    context = {
        'list_watchlist': data_watchlist,
        'nama': 'Riona Adani Ghaisani',
        'npm' : '2106750995'
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from todolist.models import Task
from todolist.forms import TaskForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core import serializers
from datetime import datetime


# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        'list_task': data_task,
    }
    return render(request, "todolist.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

def add_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user=User.objects.get(username=request.user.username)
            task.save()
            return redirect('todolist:show_todolist')
    
    context = {'form':form}
    return render(request, 'add-task.html', context)

def change_status(request):
    if request.method == "POST":
        task = Task.objects.get(id=request.POST["id"])
        task.status = not(task.status)
        task.save()
    return redirect('todolist:show_todolist')

def delete_task(request):
    if request.method == "POST":
        task = Task.objects.get(id=request.POST["id"])
        task.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    return render(request, "todolist-ajax.html")

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.method == "POST":
        new_title = request.POST.get('title')
        new_description = request.POST.get('description')

        new_task = Task(
            user = User.objects.get(username=request.user.username),
            date = datetime.now(),
            title = new_title,
            description = new_description,
        )
        
        new_task.save()
    
    return render(request, "todolist-ajax.html")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 2 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for judul in list_watchlist %}
    <tr>
        <th>{{judul.watched}}</th>
        <th>{{judul.title}}</th>
        <th>{{judul.rating}}</th>
        <th>{{judul.release_date}}</th>
        <th>{{judul.review}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/add-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Tambah Task Baru</title>
{% endblock meta %}

{% block content %}  

<div class = "add_task" style="text-align:center ;">
    
    <h1>Tambah Task Baru</h1>  

        <form method="POST" >  
            {% csrf_token %} 
            <table class="table solid border w-auto" style="text-align:left;margin-right:auto;margin-left:auto;margin-top:25px;">  
                {{ form.as_table }}  
            </table> 
            <td><input class="btn" type="submit" name="submit" value="Tambah Task" style="background-color: hsl(210, 31%, 68%);"/></td>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login" style="text-align:center;">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="table solid border w-auto" style="margin-left:auto;margin-right:auto;margin-top:25px;">
            <tr>
                <td style="vertical-align:middle;">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="vertical-align:middle;">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <input class="btn login_btn" style="background-color: hsl(210, 31%, 68%); margin-bottom:20px;" type="submit" value="Login">
    </form>
   
        
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}  
        
    Belum mempunyai akun? <a class="btn" href="{% url 'todolist:register' %}" style="background-color: hsl(210, 31%, 68%);">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login" style="text-align:center;">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table class="table solid border w-auto" style="text-align:left;margin-right:auto;margin-left:auto;margin-top:25px;"> 
                {{ form.as_table }}  
            </table>  
            <td><input class="btn" type="submit" name="submit" value="Daftar" style="background-color: hsl(210, 31%, 68%);"/></td>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist-ajax.html
{% extends 'base.html' %}

{% block content %}

    <h1>To Do List</h1>

    <h5>User: {{user}}</h5>

    <div class = "add_task">

    <table id="table"></table>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        async function show_table(){
        document.getElementById("table").innerHTML = ""
        let htmlString = `<tr>
            <th>Date</th>
            <th>Title</th>
            <th>Description</th>
        </tr>`
        $.get("{% url 'todolist:show_json' %}", function(data){
            for(var i = 0; i < data.length; i++){
                htmlString += `\n<tr>
                    <th>${data[i].fields.date}</th>
                    <th>${data[i].fields.title}</th>
                    <th>${data[i].fields.description}</th>
                </tr>`
            }
            document.getElementById("table").innerHTML = htmlString
        })        
    }

        $(document).on('submit', '#form_add', function(e) {
            e.preventDefault()
            show_table()
            $.ajax({
                type:"POST",
                url:"{% url 'todolist:add_task_ajax' %}",
                data:{
                    date:$("#date").val(),
                    title:$("#title").val(),
                    description:$("#description").val(),
                    csrfmiddlewaretoken:'{{ csrf_token }}',
                },
                dataType: 'json',
            })
            document.getElementById("form_add").reset();
            show_table()
        })

        show_table()
    </script>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Tambah Task</button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Task Baru</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <!-- Isi Form -->
            <form id="form_add" method="POST" action="">
                <div class="modal-body">
                        <p>Title</p>
                        <p><input id="title" type="text" name="title" placeholder="Title" class="form-control"></p>
                        <p>Description</p>
                        <p><input id="description" type="text" name="description" placeholder="Description" class="form-control"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" data-bs-dismiss="modal" class="btn btn-primary">Tambah Task</button>
                </div>
            </form>
        </div>
    </div>
    </div>


    <button><a href="{% url 'todolist:add_task' %}">Tambah Task Baru</a></button>
    <button><a href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <h5 class="navbar-brand mb-0 h1">To Do List</h5>
    <a class="btn" href="{% url 'todolist:logout' %}" role="button" style="background-color: hsl(210, 31%, 68%);" >Logout</a>
  </div>
</nav>

<div class = "add_task">

<header>
  <h3 style="text-align:center;">User:</h3>
  <h3 style="text-align:center;margin-bottom:20px;">{{user}}</h3>
</header>

<div class="card-deck">
  {% for task in list_task %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{task.title}}</h5>
        {% if task.status %}  
          <h6 class="card-subtitle mb-2 text-muted">Selesai</h6>
        {% else %}
          <h6 class="card-subtitle mb-2 text-muted">Belum Selesai</h6>
        {% endif %}
        <p class="card-text">{{task.description}}</p>

      <div class="container-button">
        <div class="change-status">
          <form method="POST" action="{% url 'todolist:change_status' %}">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{task.id}}">
            <button class="btn btn-primary btn-sm" type="submit">Change Status</button>
          </form>
        </div>
        <div class="delete">
          <form method="POST" action="{% url 'todolist:delete_task' %}">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{task.id}}">
            <button class="btn btn-primary btn-sm" type="submit">Delete Task</button>
          </form>
        </div>
      </div>
      </div>
      <div class="card-footer">
        <small class="text-muted">{{task.date}}</small>
    </div>
    </div>
  {% endfor %}
</div>
  
<footer>
  <a button class="btn btn-lg" style="background-color: hsl(210, 31%, 68%);" href="{% url 'todolist:add_task' %}">Tambah Task Baru</a>
</footer>

{% endblock content %}